config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  get '/signup' => 'parents#new'
  get '/login' => 'sessions#new'
  get '/auth/facebook/callback' => 'sessions#create'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/parents' => 'parents#new'
  get '/children' => 'children#new'
  get '/parents/teachers/new' => 'teachers#new'
  post '/parents/teachers' => 'teachers#create'
  resources :schools, only: [:show, :index] do
    resources :teachers, only: [:show, :new, :create, :index] 
  end
  resources :teachers, only: [:create, :show, :index, :new]

  resources :children, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :parents, only: [:new, :show, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/child.rb
class Child < ApplicationRecord
    belongs_to :parent
    belongs_to :teacher, optional: true

    validates :name, presence: true
    validates :age, presence: true

    scope :order_by_age, -> { order(age: :asc) }
end

app/models/parent.rb
class Parent < ApplicationRecord
    has_secure_password
    has_many :children, dependent: :destroy
    has_many :teachers, through: :children

    validates :email, presence: true
    validates :email, uniqueness: true

    def self.find_or_create_by_omniauth(auth_hash)
      oauth_email = auth_hash['info']['email']
      #logged in with FB before
      if @parent = Parent.find_by(email: oauth_email)
          @parent
      else
          #logged in with FB first time
          @parent = Parent.create(email: oauth_email, password: SecureRandom.hex)
      end
    end
    
end

app/models/school.rb
class School < ApplicationRecord
    has_many :teachers
    has_many :children, through: :teachers

    validates :name, presence: true

    def self.format_date
        self.created_at..strftime("%Y-%m-%d")
    end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    belongs_to :school
    has_many :children
    has_many :parents, through: :children

    validates :name, presence: true
    validates :grade_taught, presence: true

    scope :order_by_grade, -> { order(grade_taught: :asc) }
    scope :order_by_name, -> { order(name: :asc) }

    def name_and_grade
        "#{self.name}, #{self.grade_taught.ordinalize} grade"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    before_action :require_login
    
    private

    def require_login
        unless logged_in? && current_user
          flash[:error] = "You must be logged in to access this section"
          redirect_to login_path # halts request cycle
        end
      end

    def logged_in?
        session[:user_id] 
    end
  
    def current_user
      @current_user ||= Parent.find(session[:user_id]) if session[:user_id]     
    end
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
    before_action :set_child, only: [:show, :edit, :update, :destroy]

    def new
        @child = Child.new 
        @teachers = Teacher.all.order_by_grade
    end

    def create
        @child = Child.new(child_params)
        @child.parent_id = current_user.id
       if  @child.save   
        redirect_to parent_path(current_user)
       else 
        render :new
       end
    end

    def show 
    end

    def edit
        @teachers = Teacher.all.order_by_grade
    end

    def update
        @child.update(child_params)
        @child.save
        redirect_to @child
    end

    def destroy
        @child.destroy
        redirect_to parent_path(@child.parent_id)
    end
    
    private 

    def child_params
        params.require(:child).permit(:name, :age, :parent_id, :teacher_id)
    end

    def set_child
        @child = Child.find_by(id: params[:id])
    end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
    skip_before_action :require_login, only: [:new, :create]
    before_action :set_parent, only: [:edit, :update, :destroy]
    
    def new
        @parent = Parent.new
    end

    #signup
    def create
        @parent = Parent.new(parent_params)
        if @parent.save
            session[:user_id] = @parent.id
            redirect_to @parent
        else
            render :new
        end
    end

    def show
        set_parent
        @child = Child.find_by(parent_id: params[:parent_id])
        @parent.children.order_by_age
        # @child.order_by_age
    end

    def edit
    end

    def update
        @parent.update(parent_params)
        @parent.save
        redirect_to @parent
    end

    def destroy
        @parent.destroy
        redirect_to root_path
    end





    private

    def set_parent 
        @parent = Parent.find(params[:id])
    end

    def parent_params
        params.require(:parent).permit(:email, :password, :admin)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
    
  def index
       @schools = School.all   
       respond_to do |f|
        f.html 
        f.json {render json: @schools}
       end
   
   end

   def show
       @school = School.find(params[:id]) 
       @teacher = @school.teachers.build
       respond_to do |f|
        f.html 
        f.json {render json: @school, include: [:teachers]}
       end
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :require_login, only: [:new, :create, :index]


    def new 
      @parent = Parent.new 
    end

    #login
    def create
      #login with omniauth
      if auth_hash 
        @parent = Parent.find_or_create_by_omniauth(auth_hash)
        session[:user_id] = @parent.id
        redirect_to parent_path(@parent)
      #normal login flow
      else
        @parent = Parent.find_by(email: params[:parent][:email])
         if @parent && @parent.authenticate(params[:parent][:password])
            session[:user_id] = @parent.id
            redirect_to parent_path(@parent)
         else
          flash[:msg] = "Please fill out all fields."
            redirect_to login_path
         end
       end
    end

    #logout
    def destroy 
      session.clear
      redirect_to '/'
    end

    private 

    def auth_hash
      request.env['omniauth.auth']
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new
       if params[:school_id] && @school = School.find_by_id(params[:school_id])
         @teacher = @school.teachers.build
       else
         @teacher = Teacher.new 
       end
   end

   def create
       @school = School.find_by_id(params[:school][:id])
       @teacher = @school.teachers.build(teacher_params)
       
       if @teacher.save
        render json: @teacher
       end  
   end

   def show 
     @teacher = Teacher.find_by_id(params[:id]) 
   end

   def index
     @teachers = Teacher.all.order_by_grade   

     respond_to do |f|
      f.html 
      f.json {render json: @teachers}
     end
   end

   private 

   def teacher_params
     params.require(:teacher).permit(:name, :grade_taught, :school_id)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/children/_form.html.erb
<%= form_for @child do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :placeholder => (@child.errors.full_messages_for(:name).first) %>
    <%= f.label :age %>
    <%= f.number_field :age, :placeholder => (@child.errors.full_messages_for(:age).first) %>
    <%= f.label "Choose what Grade your Child is entering:", for: :child_teacher_id %>
    <%= content_tag :div, class: "input-field" do %>
    <%= f.collection_select :teacher_id, @teachers, :id, :name_and_grade %> 
    <% end %>
    <%= f.submit %>
    <% end %>

app/views/children/edit.html.erb
<h1>Edit your Child's Information </h1>
<%= render 'form' %>

app/views/children/new.html.erb
<h1>New Child Sign Up!</h1>
<%= render 'form' %>

app/views/children/show.html.erb
<h2><%= @child.name %>'s School Page</h2>

<% if @child.teacher %>
  <h4><%= link_to @child.teacher.name, teacher_path(@child.teacher_id) %> is <%= @child.name %>'s <%= @child.teacher.grade_taught.ordinalize %> grade Teacher </h4>
<% end %>

<% if @child.parent == current_user %>
  <%= button_to 'Edit Childs Information', edit_child_path(@child), method: "get" %>
 <%= form_tag child_path(@child.id), method: "delete" do %>
    <%= submit_tag "Delete Childs Information" %>
 <% end %>
<% end %>
<%= button_to 'Back to your Account Page', parent_path(@child.parent), method: "get" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schoolapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>

    <div class="container"> 
    <h1>SCHOOL REGISTRATION</h1>
    </div>

    <nav>
    <div class="nav-wrapper blue darken-1">
    <div class="container"> 
      <ul>
      <% if !logged_in? %>
      <li> <%= link_to 'Login', login_path %></li>
      <li><%= link_to('Login with Facebook', '/auth/facebook') %></li>
      <% elsif current_user %>  
      <li><%= link_to 'Check your School Options', schools_path, id: "all_schools" %></li>
      <li><%= link_to 'Back to Signup', root_path %></li> 
      <li><%= link_to 'Your Home Page', parent_path(current_user) %></li>
      <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
     <% end %>
      </ul>
      </div>
    </div>
  </nav>
  
  <div id="background " class="container"> 
  <div id="schools-container">
     <%= yield %>
   </div>
   </div> 


  </body>
</html>

app/views/parents/_form.html.erb
<%= form_for @parent do |f| %>
    <%= f.label 'Email' %>
    <%= f.text_field :email, :placeholder => (@parent.errors.full_messages_for(:email).first) %>
    <%= f.label 'Password' %>
    <%= f.password_field :password, :placeholder => (@parent.errors.full_messages_for(:password).first)%>
    <%= f.label :admin, for: "admin_checkbox" do %>      
      <%= f.check_box :admin, id: "admin_checkbox" %> 
      <%= content_tag(:span, 'Are you an Admin?') %> 
     <% end %> 
     <br>
 <br>
    <%= f.submit %>
    <% end %>
   

app/views/parents/edit.html.erb
<h1>Edit your Account </h1>
<%= render 'form' %>

app/views/parents/new.html.erb
<h1>Register your Account </h1>
<%= render 'form' %>

app/views/parents/show.html.erb
<% if @parent == current_user %>
<h2>Account Login: <%= @parent.email %></h2>
<h3>Admin Status: <%= @parent.admin %></h3>
<h4>Registered Children:</h4>
 <ol>
   <% @parent.children.each do |child| %>
     <li> <%= link_to "#{child.name}, #{child.age}", child_path(child)%> is in <%= link_to child.teacher.name, teacher_path(child.teacher_id) %>'s class. </li>
   <% end %>
  </ol>

<div class="row">
  <%= button_to 'Register your Child', new_child_path, method: "get" %>
  <%= button_to 'Edit your Account', edit_parent_path, method: "get" %>
 
  <%= form_tag parent_path(@parent.id), method: "delete" do %>
   <%= submit_tag "Delete your Account" %>
  <% end %>
</div>
<% else %>
<h3>You do not have access to this page.</h3>
<% end %>

app/views/schools/index.html.erb
<ul>
  <% @schools.each do |school| %>
    <li><%= link_to school.name, school_path(school) %></li>
  <% end %>
</ul> 

app/views/schools/show.html.erb
<h1><%= @school.name %></h1>

<div id="all_teachers"></div>

<%= button_to 'Show All Teachers', school_teachers_path(@school), method: "get", id: "teachers" %>

<% if current_user.admin %>
  <%= button_to 'Add New Teacher', new_school_teacher_path(@school), method: "get" %>
<% end %>

app/views/teachers/index.html.erb
<ul>
  <% @teachers.each do |teacher| %>
   <li>Name: <%= link_to teacher.name, teacher_path(teacher) %>, Grade: <%= teacher.grade_taught %> </li>
  <% end %>
</ul> 

app/views/teachers/new.html.erb
<h1>Add a Teacher</h1>
<%= form_for @teacher, html:{id: 'new_teacher'} do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :placeholder => (@teacher.errors.full_messages_for(:name).first) %>
    <%= f.label :grade_taught %>
    <%= f.text_field :grade_taught, :placeholder => (@teacher.errors.full_messages_for(:grade_taught).first) %>
    <% if @school %>
       <%= hidden_field_tag 'school_id', @school.id %>
    <% else %>
       <%= label_tag 'Choose School:' %>
       <%= collection_select(:school, :id, School.all, :id, :name) %> 
    <% end %>
   <%= f.submit %>
<% end %>

app/views/teachers/show.html.erb
<h3><%= @teacher.name %> teaches <%= @teacher.grade_taught.ordinalize %> grade.</h3>

<h4>Children in <%="#{@teacher.name}"%>'s Class: </h4>
<ol>
 <% @teacher.children.each do |child| %>
  <li>Name: <%= link_to child.name, child_path(child)  %>, Emergency Contact: <%= link_to child.parent.email, parent_path(child.parent_id) %></li>

 <% end %>
</ol>